---
title: "Human Activity Recognition - Samsung Galaxy S Smartphone dataset"
output: html_document
---

This dataset is obtained from **UCI Machine Learning Repository**. It is built from the recordings of 30 persons perforing the below activities

  - WALKING 
  - WALKING_UPSTAIRS
  - WALKING_DOWNSTAIRS
  - SITTING
  - STANDING
  - LAYING
  
Each record has 561 features with the time and frequency variables, with its activity labels and an identifier to the subject who carried out the experiment.

You can find the dataset in the UCI HAR Dataset directory. The various files in the dataset are explained below

  - *test/Subject_test.txt* : Each row identifies the subject who performed the activity for each                                   window sample. Its range is from 1 to 30
  - *test/X-test.txt* : Test set
  - *test/y_test.txt* : Test labels
  - *train/Subject_train.txt* : Each row identifies the subject who performed the activity for each                                   window sample. Its range is from 1 to 30 
  - *train/X_train.txt* : Train set
  - *train/y_train.txt* : Train labels
  - *activity_label.txt* : Links the class labels with their activity name
  - *features.txt* : List of all features
  - *features_info.txt* : Shows information about the variables used on the feature vector
  
## Features

The features selected for this dataset come from the accelerometer and gyroscope 3-axial signals in the X,Y and Z directions.

These signals were used to estimate variables of the feature vector for each pattern:  

  - tBodyAcc-XYZ
  - tGravityAcc-XYZ
  - tBodyAccJerk-XYZ
  - tBodyGyro-XYZ
  - tBodyGyroJerk-XYZ
  - tBodyAccMag
  - tGravityAccMag
  - tBodyAccJerkMag
  - tBodyGyroMag
  - tBodyGyroJerkMag
  - fBodyAcc-XYZ
  - fBodyAccJerk-XYZ
  - fBodyGyro-XYZ
  - fBodyAccMag
  - fBodyAccJerkMag
  - fBodyGyroMag
  - fBodyGyroJerkMag
  - gravityMean
  - tBodyAccMean
  - tBodyAccJerkMean
  - tBodyGyroMean
  - tBodyGyroJerkMean

The set of variables that were estimated from these signals are: 

  - mean(): Mean value
  - std(): Standard deviation
  - mad(): Median absolute deviation 
  - max(): Largest value in array
  - min(): Smallest value in array
  - sma(): Signal magnitude area
  - energy(): Energy measure. Sum of the squares divided by the number of values. 
  - iqr(): Interquartile range 
  - entropy(): Signal entropy
  - arCoeff(): Autorregresion coefficients with Burg order equal to 4
  - correlation(): correlation coefficient between two signals
  - maxInds(): index of the frequency component with largest magnitude
  - meanFreq(): Weighted average of the frequency components to obtain a mean frequency
  - skewness(): skewness of the frequency domain signal 
  - kurtosis(): kurtosis of the frequency domain signal 
  - bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
  - angle(): Angle between to vectors.

## Transformations applied to clean the data

The training data is obtained from Subject_train.txt, X_train.txt, y_train.txt. Similarly the test data is obtained from Subject_test, X_test, y_test. And then they were merged to form one full dataset that contains both test and training data. Features (or column names) are added to the dataset as headers. The entire dataset is written to a file named *tidydata.csv*

A new column is added to the dataset, ActivityName, whose values are read from the 'activity_labels.txt'

From the dataset, the mean and standard deviation measurements are extracted and the mean of each mean and standard deviation is calculated for each activity.

The average of each mean and standard deviation variable - grouped by activity and subject - was performed on the data to produce the *meanSD_data.csv* dataset. The tidydata.txt dataset contains the average of mean and standard deviation variables for each activity performed by each subject.

